import React, { useState } from 'react';
import { X, Printer, Copy, Check, Download, FileText } from 'lucide-react';
import { DecisionResult } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  decision: DecisionResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, decision }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    let md = `# The Tiebreaker: Decision Analysis Report\n\n`;
    md += `**Question:** ${decision.question}\n\n`;
    if (decision.context) {
      md += `**Context & Constraints:** ${decision.context}\n\n`;
    }
    md += `**Date:** ${new Date(decision.createdAt).toLocaleDateString()}\n\n`;
    md += `---\n\n`;

    md += `## 🏆 The Tiebreaker Verdict\n\n`;
    md += `**Recommended Choice:** ${decision.verdict.recommendedOptionTitle} (${decision.verdict.confidencePercentage}% confidence)\n\n`;
    md += `**The Deciding Factor:** ${decision.verdict.theTiebreakerFactor}\n\n`;
    md += `**Rationale:** ${decision.verdict.summaryRationale}\n\n`;

    md += `### Critical Blind Spots to Watch:\n`;
    decision.verdict.keyRisksToWatch.forEach((risk) => {
      md += `- ${risk}\n`;
    });
    md += `\n`;

    md += `### Action Plan (Next 48h - 7d):\n`;
    decision.verdict.recommendedNextSteps.forEach((step) => {
      md += `- ${step}\n`;
    });
    md += `\n`;

    md += `**Gut-Check Question:** "${decision.verdict.gutCheckQuestion}"\n\n`;
    md += `---\n\n`;

    md += `## ⚖️ Pros and Cons Breakdown\n\n`;
    decision.options.forEach((opt) => {
      md += `### ${opt.title} (Reversibility: ${opt.reversibility})\n`;
      md += `*${opt.summary}*\n\n`;
      md += `**Pros:**\n`;
      opt.pros.forEach((p) => {
        md += `- [${p.weight.toUpperCase()}] ${p.text} ${p.category ? `(${p.category})` : ''}\n`;
      });
      md += `\n**Cons:**\n`;
      opt.cons.forEach((c) => {
        md += `- [${c.weight.toUpperCase()}] ${c.text} ${c.category ? `(${c.category})` : ''}\n`;
      });
      md += `\n`;
    });

    md += `---\n\n`;
    md += `## 🧭 SWOT Analysis\n\n`;
    decision.options.forEach((opt) => {
      md += `### SWOT: ${opt.title}\n`;
      md += `- **Strengths:** ${opt.swot.strengths.join('; ')}\n`;
      md += `- **Weaknesses:** ${opt.swot.weaknesses.join('; ')}\n`;
      md += `- **Opportunities:** ${opt.swot.opportunities.join('; ')}\n`;
      md += `- **Threats:** ${opt.swot.threats.join('; ')}\n\n`;
    });

    md += `---\n*Generated by The Tiebreaker AI Decision Engine*`;
    return md;
  };

  const handleCopyMarkdown = async () => {
    const md = generateMarkdownReport();
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(decision, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `tiebreaker-decision-${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-900/60 backdrop-blur-xs no-print">
      <div className="w-full max-w-lg rounded-2xl border border-stone-200 bg-white shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-stone-200 px-6 py-4 bg-stone-50/80">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-amber-600" />
            <h3 className="text-base font-bold text-stone-900 font-display">Export & Share Decision</h3>
          </div>
          <button
            type="button"
            id="close-export-modal-btn"
            onClick={onClose}
            className="rounded-lg p-1.5 text-stone-400 hover:bg-stone-200 hover:text-stone-700 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-4">
          <p className="text-xs sm:text-sm text-stone-600">
            Save this decision analysis for your personal records, print a clean PDF briefing, or copy as Markdown for Notion, Obsidian, or team memos.
          </p>

          <div className="space-y-3">
            {/* Print / PDF button */}
            <button
              type="button"
              id="export-print-btn"
              onClick={handlePrint}
              className="w-full flex items-center justify-between p-3.5 rounded-xl border border-stone-200 hover:border-stone-400 hover:bg-stone-50 transition-all text-left group"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-stone-100 text-stone-700 group-hover:bg-stone-900 group-hover:text-white transition-colors">
                  <Printer className="h-4 w-4" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-stone-900">Print / Save as PDF</h4>
                  <p className="text-xs text-stone-500">Formats a clean, distraction-free document layout</p>
                </div>
              </div>
            </button>

            {/* Markdown Copy */}
            <button
              type="button"
              id="export-markdown-btn"
              onClick={handleCopyMarkdown}
              className="w-full flex items-center justify-between p-3.5 rounded-xl border border-stone-200 hover:border-stone-400 hover:bg-stone-50 transition-all text-left group"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-stone-100 text-stone-700 group-hover:bg-stone-900 group-hover:text-white transition-colors">
                  {copied ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
                </div>
                <div>
                  <h4 className="text-sm font-bold text-stone-900">
                    {copied ? 'Copied to Clipboard!' : 'Copy Formatted Markdown'}
                  </h4>
                  <p className="text-xs text-stone-500">Perfect for pasting into Notion, Google Docs, or Slack</p>
                </div>
              </div>
            </button>

            {/* JSON Download */}
            <button
              type="button"
              id="export-json-btn"
              onClick={handleDownloadJSON}
              className="w-full flex items-center justify-between p-3.5 rounded-xl border border-stone-200 hover:border-stone-400 hover:bg-stone-50 transition-all text-left group"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-stone-100 text-stone-700 group-hover:bg-stone-900 group-hover:text-white transition-colors">
                  <Download className="h-4 w-4" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-stone-900">Download Raw JSON</h4>
                  <p className="text-xs text-stone-500">Structured data backup for developers</p>
                </div>
              </div>
            </button>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end border-t border-stone-200 px-6 py-3 bg-stone-50/80">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-stone-300 bg-white px-4 py-2 text-xs font-semibold text-stone-700 hover:bg-stone-100"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
